### ISSUE TITLE
New third party controller support request

### ISSUE THREAD

**Issue by peteranmu** [360Controller/360Controller#1009]
### Type of Controller
Third party Xbox 360 controller

### OS Version
macOS Catalina 10.15.3

### Driver Version
v1.0.0-alpha.5

### Connection Method
Wired

### Device Name and Info
>Device Name:BETOP BTP-2185
<br/>Product ID:0x028e
<br/>Vendor ID:0x045e

### Response of Controller
Guide button light up, but can't be used or show in the preference pane of driver.

### Response in Preference Pane
Not show in the preference pane of the driver.

**Comment by FranticRain** [comment]
This is a knock-off controller that imitates the official Microsoft Xbox controllers. We have branded these "counterfeit" controllers, and do not support them. The vendor and product ID combination are already included in the driver, so they would match properly if the controller followed the standard protocol for pairing with an Xbox device. Since they do not follow the standard protocol, we do not support these types on controllers. Sorry.
