### ISSUE TITLE
Wired Third Party Xbox 360 controller not working

### ISSUE THREAD

**Issue by ijoaum** [360Controller/360Controller#1047]
### Type of Controller
Xbox 360

### OS Version
Catalina 10.15.4 (19E287)

### Driver Version
1.0.0-alpha.5

### Connection Method
Wired

### Device Name and Info
(If you don't know this information, please refer to the README for how to find it. Enter N/A if not applicable)

Controller:
  Product ID:	0x028e
  Vendor IDr:	0x045e  (Microsoft Corporation)
  Version:	1.14
  Serial Number:	1105373
  Speed:	Até 12 Mb/s
  Fabricante:	Holtek
  Location ID:	0x14200000 / 6
  Corrente Elétrica Disponível (mA):	500
  Corrente de Funcionamento Extra (mA):	0

### Response of Controller
Light blinks.

### Response in Preference Pane
No devices found on Pref Pane.

### Detailed Explaination of Issue
It is a third-party controller and I just think it does not have de right driver for it. 
The controller works well on chrome https://html5gamepad.com/

**Comment by FranticRain** [comment]
Looks like this is a knock-off controller that copies the vendor and product ID of a real Xbox controller. We don't support controllers like this. Controllers need to conform to the Xbox controller specification, otherwise they won't work with the driver. Since this device violates the USB and Xbox specifications, we cannot and will not support it.
