### ISSUE TITLE
Xbox 360 USB Controller Calibration issue

### ISSUE THREAD

**Issue by amalryc** [360Controller/360Controller#1058]
### Type of Controller
Replace this text with: Original Xbox 360 USB

### OS Version
Mojave 10.14.6

### Driver Version
Version 1.0.0-alpha.2

### Connection Method
USB Built in Cable 

### Device Name and Info
Product ID:	0x028e
Vendor ID:	0x045e  (Microsoft Corporation)
Version:	1.10
Serial Number:	0000001
Speed:	Up to 12 Mb/sec
Manufacturer:	Inno GamePad..
Location ID:	0x14100000 / 2
Current Available (mA):	500
Current Required (mA):	500
Extra Operating Current (mA):	0

### Response of Controller
The controller Lights up well and the vibration works as well. 

### Response in Preference Pane
Yes, it shows up and all the buttons work nicely except for the joysticks. 

### Detailed Explaination of Issue
The problem is with Joysticks the calibration. The sticks do not move smoothly in the graphic representation and are not sync properly. The range of movement seems to be messed up since It only starts moving after the sticks are half-way through and it reaches the wall before the stick reach the limit. Also, I noticed that this movement is really fast and out of control which makes it impossible for precision uses such as aiming, etc.

**Comment by FranticRain** [comment]
This is a symptom of knock-off controllers. We don't support these devices since they don't follow the Xbox specification, and then declare themselves as Xbox devices by stealing the vendor and product ID combination of real controllers. Because they follow neither the Xbox, nor the USB specification, we don't support their quirks.
