### ISSUE TITLE
I need help.

### ISSUE THREAD

**Issue by TameDabeastman2** [360Controller/360Controller#1066]
### Type of Controller
Xbox One

### OS Version
10.15.2

### Driver Version
360Controller 1.0.0-alpha.5

### Connection Method
Replace this text with: Wired, Bluetooth, 
### Device Name and Info
N/A
### Response of Controller
Does the guide button light up? Does it vibrate? yes, and yes but the 360controller software doesn't pick it up

### Response in Preference Pane
yes

### Detailed Explaination of Issue
The issue is when I run Roblox. I just want to play some games with it and it doesn't work. I am very big sad.

**Comment by FranticRain** [comment]
The driver does not provide any sort of compatibility for individual games beyond what is provided in the preference pane. The driver simply sends button data to the operating system. Once it does that, control is out of the driver's hands. Since Apple does not provide any standardized means of interacting with controllers in macOS, every game uses a different method to read controller data. We cannot provide individual fixes for each game within the controller. That simply isn't feasible. It is the responsibility of game developers to support controllers, not the other way around. We cannot and will not provide support for individual games. If you are using an Xbox One controller, we can recommend that you use the "Pretend to be an Xbox 360 Controller" option in the "Advanced" menu for better game compatibility. Beyond that, there is nothing we can do.
