### ISSUE TITLE
My MAC cannot see my Logitech gamepad F310

### ISSUE THREAD

**Issue by frodoe7** [360Controller/360Controller#1209]
### Type of Controller
All

### OS Version
Big Sur 11.4

### Driver Version
0.16.11

### Connection Method
Wired

### Device Name and Info
Logitech Gamepad F310

### Response of Controller
I tried the gamepad on windows and it working normally

but in my Mac it does not work, even after clicking the mode button , it does not open this white led (looks no power in the device)

### Response in Preference Pane
It does not see the gamepad at all (no connected devices/controllers)

**Comment by toshe** [comment]
@frodoe7 Can you check if this device is in `360Controller/360Controller/Info.plist`? If it's not listed there, add a **new** entry following the pattern of pre-existing controllers. Change the values `idProduct` and `idVendor` for your new controller entry. You have to convert the hex values to decimal. Once done, please submit a Pull Request so that the device can be supported in a new release.

**Comment by frodoe7** [comment]
@toshe 
It worked after following this:
https://steamcommunity.com/discussions/forum/2/3004429475624592660/
