### ISSUE TITLE
Wake up mac connect problem

### ISSUE THREAD

**Issue by charles** [360Controller/360Controller#13]
Hi,
I'm using drivers version 0.13.1 and when my mac wake up form sleep I can't connect the wireless xbox 360 controller, all 4 lights blink. Is necessary disconect the receptor from USB and connect again to working. Is this a bug? There is a fix for that?
My iMac is Mavericks OS X 10.9.4
Thanks,
Charles

**Comment by burito** [comment]
Wireless controller.

I wake from sleep, the ring is flashing, but it's recognised by the SysPref app, force feedback doesn't work.

I unplugged the usb-wireless thing, now the controller leds are circling (clockwise), and force feedback works.

So I plugged in a wired controller, no force feedback, but the p2 led came on as expected. I select controller 2 in the SysPref app, and the leds circle.

Now I turn on the second wireless controller, and the leds on wired controller go out. Wifi2 has p3 Led lit as expected, but the SysPref app claims that wired is now controller 3, and wifi2 is now controller 2. When I select wifi2 and wired1 their leds start circling.

**Comment by bearmountainbranch** [comment]
Wired controller plugged in.
If plugged in before waking up from sleep, LEDs never stop blinking. 
If plugged in before boot up, LEDs never light up.

I tried to disable code-signing and build the project but build failed due to code signing. :S

Anyway, how about ask to be notified computer power on/wake up (see: https://developer.apple.com/library/mac/qa/qa1340/_index.html ). I guess 360Daemon.m is the place to do it. Then when notified iterate over io devices / objects and if xbox 360 controller is found try to configure it again.

How would that work?

**Comment by maxengel** [comment]
I'm having this problem as well. The wireless controller won't work if the controller is connected through a USB hub. If I unplug/replug the dongle the pref pane will then recognize it.

**Comment by cuthead** [comment]
I use Parallels Desktop 11 with Windows XP SP3 CN installed Microsoft official Xbox 360 controller Driver,then sleep and wake up,disconnect and connect Xbox 360 controller by using Parallels Desktop 11 USB function,4 lights stop blinks.That solved my problem,I think Parallel Desktop 11 can "soft" disconnect Xbox 360 controller.

**Comment by MaddTheSane** [comment]
This should be fixed in commit b87af7ce0076ddd2bfee76b04cd7d90f16d335e6.
