### ISSUE TITLE
El Captian Does not recognise it

### ISSUE THREAD

**Issue by dralism08** [360Controller/360Controller#190]
Hi
I am using driver 0.15 beta 3 and it seems that my mac does not recognise the controller as I got a notification message once I connect it that I am using charge and play cable, however when I enter system preference to the Xbox 360 controllers I got no device found.
Note: I am using a wired controller I do not have a wireless adapter 
Cheers

**Comment by FranticRain** [comment]
Wireless Xbox 360 controllers are always wireless. Using a play and charge kit does not make them wired. It simply charges the controller. In order to use a wireless controller with this driver, you will need a wireless receiver for the controller.

Turning a wireless controller into a wired controller is a feature of the Xbox One controller, however.
