### ISSUE TITLE
Confused about option "Pretend to be an Xbox 360 Controller"

### ISSUE THREAD

**Issue by dideler** [360Controller/360Controller#329]
I don't fully understand what the "Pretend to be an Xbox 360 Controller" option is for.

How it's currently documented in the README, it only seems to be used during troubleshooting.

What does it do? Should it only be enabled if an Xbox One controller isn't working?

Thanks

**Comment by FranticRain** [comment]
The Xbox One controller has a different product ID, but the same vendor ID, as the Xbox 360 controller. Some games have sloppy implementations of controller support, so they explicitly look for the vendor and product ID of the Xbox 360 controller. What that check box does, is that it makes Xbox One controllers send out the Xbox 360's PID and VID instead of its own. That way, you can trick games into using the controller.

We let the Xbox One controller show its own PID and VID normally because the hardware is more accurate, so smaller deadzones can be imposed by games, etc.

So if a game isn't working, check that box and that might fix it. If that doesn't fix it, then that game doesn't work with Xbox 360 controllers.
