### ISSUE TITLE
2 Xbox One Elite controllers (USB) seen as the same controller in-game

### ISSUE THREAD

**Issue by Ryunam** [360Controller/360Controller#341]
Hello, I would first take this opportunity to thank the developers for creating this neat and convenient driver. Xbox One controllers, especially their Elite variants, are among the best ever crafted with respect to ergonomics and overall precision, therefore it is wonderful to actually have them compatible with OS X.

That being said, the driver works wonderfully when it comes to using a single controller on games and emulators, but I'm currently experiencing an issue when connecting an additional controller through USB. Here is my setup:

Macbook Pro with Retina Display
OS X El Capitan
360Controller driver version 0.16.3
2 Elite Controllers, plugged into USB

From the Settings Menu everything seems fine: the two controllers are recognized as two different devices. However, when I go into the emulator itself (namely, RetroArch), both controllers are seen as one and it's impossible to assign inputs respectively to the 1st and the 2nd player.
Thanks in advance for any help!

**Comment by FranticRain** [comment]
Unfortunately, this is a bug with RetroArch, not with this driver. This behavior is the same for any two controllers using this driver. Even ones that are not identical. There is nothing we can do to fix this. This is 100% the fault of RetroArch.

Therefore I am going to close this issue since there is nothing we can do.
