### ISSUE TITLE
MacBook Pro 15" late 2016 compatibility (USB-C)

### ISSUE THREAD

**Issue by klopfdreh** [360Controller/360Controller#382]
Hey guys,

because I just ordered my new MacBook I just wondered if the current version of the 360Controller driver supports USB-C?

kind regards and thanks in advance

**Comment by MaddTheSane** [comment]
I have used an Xbox One controller on my 2015 MacBook using the A/V USB adaptor with no issues.
On Nov 8, 2016, at 11:34 PM, Tobias Soloschenko <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey guys,

because I just ordered my new MacBook I just wondered if the current version of the 360Controller driver supports USB-C?

kind regards and thanks in advance

**Comment by klopfdreh** [comment]
Great to hear and thanks a lot for the fast response!

I think if this is confirmed by the devs too, this issue can be closed.

**Comment by FranticRain** [comment]
Nothing about USB-C changes how this driver works. Its just another form factor for a serial connection. As long as you have a USB-C to Micro-B data cable or USB-C to USB-A female data cable, it will work.

**Comment by klopfdreh** [comment]
Thanks a lot!

/close
