### ISSUE TITLE
Not recognizing the controller

### ISSUE THREAD

**Issue by Cryphunter** [360Controller/360Controller#409]
I downloaded this and it wasn't working with the game i was trying it on. downloaded the first version you released before all these. that one didn't work so i tried to uninstall but your directions led me to no way on uninstalling the program. so i installed this one again thinking i messed something up and now its not recognizing the controller and the previous program still can't be deleted.

**Comment by FranticRain** [comment]
Install the latest version over the old version. Then, you can uninstall the driver by following the instructions found here: https://github.com/360Controller/360Controller#uninstallation This will uninstall both versions of the driver.

The driver does not provide any sort of compatibility for individual games beyond what is provided in the preference pane. The driver simply sends button data to the operating system. Once it does that, control is out of the driver's hands. Since Apple does not provide any standardized means of interacting with controllers in macOS, every game uses a different method to read controller data. We cannot provide individual fixes for each game within the controller. That simply isn't feasible. It is the responsibility of game developers to support controllers, not the other way around. We cannot and will not provide support for individual games. If you are using an Xbox One controller, we can recommend that you use the "Pretend to be an Xbox 360 Controller" option in the "Advanced" menu for better game compatibility. Beyond that, there is nothing we can do.
