### ISSUE TITLE
Wired X360 Controller's right stick not recognized in TWDS02

### ISSUE THREAD

**Issue by N3M1C0** [360Controller/360Controller#442]
Hi ! 
This seems like the right place to submit this kind of issue, forgive me if it isn't.

I'm Charles and I am having problems using my wired X360 controller, especially the right stick, in _The Walking Dead Season 2_ from Telltale. Everything works except for the right stick, which is making the game really hard to play as it is a crucial part of the gameplay to use this stick.
It is known that the controller works perfectly fine within the game on Windows with the official drivers from Microsoft, so it may not be the game's fault but rather the Tattiebogle driver's, but we can't say for sure until an investigation is done. 
Another known fact : Tattiebogle worked perfectly fine in _The Walking Dead Season 1_ and works with other series released after S02 like _Game of Thrones Season 1_ or _Minecraft: Story Mode_

Could you investigate on both sides to know for sure what is the problem here? And release an update if it helps playing this series, please?
Tell me if any file on my computer could help you.

Thank you a lot for taking the time to read from me,
Best regards,
Charles

**Comment by FranticRain** [comment]
The driver does not provide any sort of compatibility for individual games beyond what is provided in the preference pane. The driver simply sends button data to the operating system. Once it does that, control is out of the driver's hands. Since Apple does not provide any standardized means of interacting with controllers in macOS, every game uses a different method to read controller data. We cannot provide individual fixes for each game within the controller. That simply isn't feasible. It is the responsibility of game developers to support controllers, not the other way around. We cannot and will not provide support for individual games. If you are using an Xbox One controller, we can recommend that you use the "Pretend to be an Xbox 360 Controller" option in the "Advanced" menu for better game compatibility. Beyond that, there is nothing we can do.
