### ISSUE TITLE
Rock Candy XBOX ONE

### ISSUE THREAD

**Issue by SuEric** [360Controller/360Controller#444]
My MAC is not detecting the following Game Controller

 Product ID: 0x0246
 Vendor ID:  0x0e6f

OS X El Capitan

**Comment by FranticRain** [comment]
This device is already in the info.plist. These PDP Rock Candy controllers have known issues with newer versions of macOS. You can see that discussion: #300. Unfortunately, there is nothing we can do about this, as it is a bug between the controller's hardware and macOS. If the driver can't see it because macOS won't show it to us, we can't do anything about it.
