### ISSUE TITLE
10.12.5 Controller No Longer Detected

### ISSUE THREAD

**Issue by JEddie20** [360Controller/360Controller#471]
Updated to 10.12.5 and I am getting the "no devices found" message in the app. SIP has been disabled which was the fix in 10.12.4 but no longer works with .5

Thanks in advance for the help!

**Comment by BorisChenCZY** [comment]
I have the same issue as well :(

**Comment by cwRichardKim** [comment]
+1

**Comment by LiamBer** [comment]
same here

**Comment by FranticRain** [comment]
What is your controller's PID/VID?

**Comment by FranticRain** [comment]
This issue is being closed due to inactivity. We can't fix issues if we don't have enough information. So periodically we close down issues that can't be resolved if they seem to have been abandoned by their creators. If your issue still persists, please open a new issue after thoroughly consulting the README and providing all information as required by the README.
