### ISSUE TITLE
Guide on proper mapping of keys

### ISSUE THREAD

**Issue by wishabhilash** [360Controller/360Controller#474]
Hi I got my XBox 360 controller successfully connected to Mac OS Sierrea. However, it doesn't work on Awesomenauts. I tried mapping the keys properly, however have no idea how to do it. Any directions would be helpful.

**Comment by FranticRain** [comment]
Use the "Pretend to be an Xbox 360 Controller" option in the "Advanced" menu of the preference pane.

The driver does not provide any sort of compatibility for individual games beyond what is provided in the preference pane. The driver simply sends button data to the operating system. Once it does that, control is out of the driver's hands. Since Apple does not provide any standardized means of interacting with controllers in macOS, every game uses a different method to read controller data. We cannot provide individual fixes for each game within the controller. That simply isn't feasible. It is the responsibility of game developers to support controllers, not the other way around. We cannot and will not provide support for individual games. If you are using an Xbox One controller, we can recommend that you use the "Pretend to be an Xbox 360 Controller" option in the "Advanced" menu for better game compatibility. Beyond that, there is nothing we can do.
