### ISSUE TITLE
macos 10.12.5 the left stick doesnt work on steam 

### ISSUE THREAD

**Issue by zyyedi** [360Controller/360Controller#484]
I don't what happen. The driver is fine, and every movement I did on 360 controller in system preference tab was recognized. That is the thing confused me. Moreover, steam identifies it as xbox 360 controller, somehow the left stick just doesn't work.

**Comment by Mirageofmage** [comment]
Did you check the controller configuration in big picture? Sometimes after a steam update, the controller settings could be reset
![big picture](https://www.howtogeek.com/wp-content/uploads/2015/12/ximg_566a3fc9697bc.png.pagespeed.gp+jp+jw+pj+ws+js+rj+rp+rw+ri+cp+md.ic.bvonuUj1sX.png)

**Comment by FranticRain** [comment]
The driver does not provide any sort of compatibility for individual games beyond what is provided in the preference pane. The driver simply sends button data to the operating system. Once it does that, control is out of the driver's hands. Since Apple does not provide any standardized means of interacting with controllers in macOS, every game uses a different method to read controller data. We cannot provide individual fixes for each game within the controller. That simply isn't feasible. It is the responsibility of game developers to support controllers, not the other way around. We cannot and will not provide support for individual games. If you are using an Xbox One controller, we can recommend that you use the "Pretend to be an Xbox 360 Controller" option in the "Advanced" menu for better game compatibility. Beyond that, there is nothing we can do.
