### ISSUE TITLE
Add option to manually assign controller number

### ISSUE THREAD

**Issue by daviewales** [360Controller/360Controller#500]
By default, the first controller plugged in becomes controller 1, the second controller 2, and so forth.

For some games, such as Rocket League, it would be helpful to be able manually assign the first controller plugged in as controller 2, the second 3, etc. This means that two people can play together where player 1 uses the keyboard, and player 2 uses the controller.

**Comment by FranticRain** [comment]
While the controllers likely gave you the impression that they are assigned a role because of the indicator lights, that is simply a cosmetic effect. In the case of the Xbox 360, the operating system assigns each controller a number. Unfortunately, in macOS, this isn't done by the operating system, and is instead the responsibility of the game. The games don't properly handle this and unfortunately it means that you have that issue. The driver has no control over who is who in this controller lineup, so unfortunately, there is nothing that we can do.
