### ISSUE TITLE
Binding Options (RT - LT)

### ISSUE THREAD

**Issue by PaulAChambers** [360Controller/360Controller#503]
![screen shot 2017-07-22 at 20 16 08](https://user-images.githubusercontent.com/30376544/28494038-a6a4e9bc-6f1a-11e7-9337-d84471f3349e.png)
After it all installed, i mapped my xbox one controller but then realised that RT and LT aren't an option, i went onto my chosen game and realised they weren't working and wondering if their was a way i could get them to work

**Comment by Rogue-Hosaka** [comment]
Hello, could you solve this problem?

**Comment by FranticRain** [comment]
The triggers are analog inputs, not digital. They cannot be remapped using the binding tool because of this.

The driver does not provide any sort of compatibility for individual games beyond what is provided in the preference pane. The driver simply sends button data to the operating system. Once it does that, control is out of the driver's hands. Since Apple does not provide any standardized means of interacting with controllers in macOS, every game uses a different method to read controller data. We cannot provide individual fixes for each game within the controller. That simply isn't feasible. It is the responsibility of game developers to support controllers, not the other way around. We cannot and will not provide support for individual games. If you are using an Xbox One controller, we can recommend that you use the "Pretend to be an Xbox 360 Controller" option in the "Advanced" menu for better game compatibility. Beyond that, there is nothing we can do.
