### ISSUE TITLE
Binding keys

### ISSUE THREAD

**Issue by locksoft** [360Controller/360Controller#519]
Hi, I'm pretty new to this app so maybe I've still not a clear idea about how it works.

I installed it in OS X El Capitan and it works perfectly. the 360 wired controller is correctly recognized and all keys work.

Now I'd like to configure it with X-Wing, where there are tons of keyboard commands. I'd like to assign them to the controller keys. Like change speed, change weapons, assign power etc.

I went to binding section of the app but I can't type "+" or "-" to assign keyboard commands to buttons. Am I doing something wrong? Do I need some other utility to do what I need?

Thanks.

**Comment by FranticRain** [comment]
The controller cannot bind to keyboard keys, that isn't how it works.

The driver does not provide any sort of compatibility for individual games beyond what is provided in the preference pane. The driver simply sends button data to the operating system. Once it does that, control is out of the driver's hands. Since Apple does not provide any standardized means of interacting with controllers in macOS, every game uses a different method to read controller data. We cannot provide individual fixes for each game within the controller. That simply isn't feasible. It is the responsibility of game developers to support controllers, not the other way around. We cannot and will not provide support for individual games. If you are using an Xbox One controller, we can recommend that you use the "Pretend to be an Xbox 360 Controller" option in the "Advanced" menu for better game compatibility. Beyond that, there is nothing we can do.
