### ISSUE TITLE
Problem with NVIDIA GE FORCE NOW - BATTLE.NET - DESTINY 2 on MAC OS HIGH SIERRA

### ISSUE THREAD

**Issue by Kami2014** [360Controller/360Controller#557]
Hi, i have a problem with NVIDIA GE FORCE NOW - BATTLE.NET - DESTINY 2 on MAC OS HIGH SIERRA. The driver find my xbox one s controller, but when i play destiny 2 isn't detected. 2 weeks ago i download a version of driver that working with NVIDIA service, but unfortunately i delete that version, so i download again the driver but the last 16.05 not work. Unfortunately I do not remember which version I downloaded. Have you an idea to resolve my problem?

**Comment by FranticRain** [comment]
The driver does not provide any sort of compatibility for individual games beyond what is provided in the preference pane. The driver simply sends button data to the operating system. Once it does that, control is out of the driver's hands. Since Apple does not provide any standardized means of interacting with controllers in macOS, every game uses a different method to read controller data. We cannot provide individual fixes for each game within the controller. That simply isn't feasible. It is the responsibility of game developers to support controllers, not the other way around. We cannot and will not provide support for individual games. If you are using an Xbox One controller, we can recommend that you use the "Pretend to be an Xbox 360 Controller" option in the "Advanced" menu for better game compatibility. Beyond that, there is nothing we can do.
