### ISSUE TITLE
360controller doesnt recognize my XBox One controller

### ISSUE THREAD

**Issue by Portal2020** [360Controller/360Controller#561]
So i bought myself a wireless XBox One controller today. I downloaded the newest version of 360controller and everything is working fine, but it doesnt recognize my controller. Can anyone help me with that?

**Comment by reteps** [comment]
go to advanced and check "enable driver". This fixed it for me.

**Comment by Portal2020** [comment]
did that, but it still doesnt recognize the controller

**Comment by Nastrella** [comment]
Hi, I'm following as I have the same issue. I'm on OS 10.13, I ticked “enable driver“, turned the computer on and off, but it still “No device found“.

**Comment by ppahv** [comment]
Hi,
I've got the same problem via Bluetooth with my Xbox One S Controller. Whereas 360controller recognises it when plugged with a USB wire, 360controller doesn't detect it when it's paired via Bluetooth.
Nonetheless, the controller works like a charm via Bluetooth, and I can use it and map it however I want in games and with the Enjoyable app. The only problem is that I can't map the two triggers RT and LT, since they're not detected when connected via Bluetooth.

**Comment by KorvinSzanto** [comment]
Try the steps listed here: https://github.com/360Controller/360Controller/issues/566#issuecomment-349858763

**Comment by Nastrella** [comment]
It's finally working for me with the steps from #566, the dialogue appeared :)
