### ISSUE TITLE
Original Xbox One controller not working

### ISSUE THREAD

**Issue by glebnerzhin** [360Controller/360Controller#563]
I'm using Mac OS X El Capitan with 10.11.6
Running the 0.16.15 driver
Product ID:	0x02d
Vendor ID:	0x045e  (Microsoft Corporation)

So, it won't recognise my controller at all, I tried enabling and disabling the driver and also uninstalling it and installing it again. What else can I do, is there any known issue or workaround? Thanks!

**Comment by MarioGiancini** [comment]
In El Capitan and Sierra  (10.11 & 10.12) I was able to my Xbox one controller working with a USB cable. 

But in **High Sierra** it doesn't seem to find the controller, even with ensuring `Enable Driver` is checked in the `Advanced` tab.

<img width="661" alt="screen shot 2017-12-10 at 10 46 52 pm" src="https://user-images.githubusercontent.com/1424538/33814982-11025ce0-ddfc-11e7-8747-19db70ddb386.png">

**Comment by sterpe** [comment]
Did you authorize the drivers in System Security Preferences after install?

**Comment by glebnerzhin** [comment]
@sterpe How would I do that?

**Comment by FranticRain** [comment]
System Preferences -> Security and Privacy -> General

**Comment by FranticRain** [comment]
This issue is being closed due to inactivity. We can't fix issues if we don't have enough information. So periodically we close down issues that can't be resolved if they seem to have been abandoned by their creators. If your issue still persists, please open a new issue after thoroughly consulting the README and providing all information as required by the README.
