### ISSUE TITLE
Won't launch

### ISSUE THREAD

**Issue by typhix** [360Controller/360Controller#609]
<img width="278" alt="screen shot 2018-02-23 at 4 37 05 pm" src="https://user-images.githubusercontent.com/36776732/36618092-ccfd33f2-18b7-11e8-9962-653e3f838c8d.png">
After downloading and installing the program, it shows in my system preferences but won't launch.

**Comment by FranticRain** [comment]
Did you allow "Drew Mills" as a developer in System Preferences -> Security & Privacy?

**Comment by FranticRain** [comment]
This issue is being closed due to inactivity. We can't fix issues if we don't have enough information. So periodically we close down issues that can't be resolved if they seem to have been abandoned by their creators. If your issue still persists, please open a new issue after thoroughly consulting the README and providing all information as required by the README.
