### ISSUE TITLE
Xbox One controller isnt recognized on mac high sierra 10.13.3

### ISSUE THREAD

**Issue by lilphil123** [360Controller/360Controller#624]
ive tried 3 different cables and it isnt working.
can anyone send me a link to a cable that'll work for sure? idk if thats the problem though

no controller pops up.
the xbox light just blinks when i plug in usb and may vibrate.

i have the old xbox controller

**Comment by lilphil123** [comment]
it isnt the cable because my controller shows up in the system repot usb hardware settings.

**Comment by lilphil123** [comment]
@FranticRain ?

**Comment by FranticRain** [comment]
https://github.com/360Controller/360Controller#xbox-one-controllers-connected-with-usb

**Comment by FranticRain** [comment]
This issue is being closed due to inactivity. We can't fix issues if we don't have enough information. So periodically we close down issues that can't be resolved if they seem to have been abandoned by their creators. If your issue still persists, please open a new issue after thoroughly consulting the README and providing all information as required by the README.
