### ISSUE TITLE
Xbox Controller saying devices not found

### ISSUE THREAD

**Issue by xboxdaddy89** [360Controller/360Controller#668]
Hi, I am having a problem with my driver. It seems whenever I plug in my controller it will not light up nor vibrate. I checked system report and it is detecting that my controller is plugged in! please help1

**Comment by FranticRain** [comment]
What type of controller is it? Is it Xbox One, 360, original Xbox? What brand is it? What is the vendor/product ID of the controller?

**Comment by FranticRain** [comment]
This issue is being closed due to inactivity. We can't fix issues if we don't have enough information. So periodically we close down issues that can't be resolved if they seem to have been abandoned by their creators. If your issue still persists, please open a new issue after thoroughly consulting the README and providing all information as required by the README.
