### ISSUE TITLE
No Device Found

### ISSUE THREAD

**Issue by Jogium** [360Controller/360Controller#676]
Hi all,

I'm reading lots of comments, and I watched a lots op videos, but still I cannot work out how to connect my Xbox One controller with my Macbook Pro.

The controller is visible in the device overview, so that shouldn't be the problem. Once I open the 360 controller program from the menu, it keeps saying: No Device Found. I reinstalled the program many times.. doesn't help.
Also in the security menu I gave 'Drew Mills' access. 

Info:
High Sierra version 10.13
360 controller 0.6.17

I hope someone can help me, thank you in advance.

**Comment by FranticRain** [comment]
Before we can help you, please consult the README and provide all necessary information so that we can help you with your issue. https://github.com/360Controller/360Controller#xbox-one-controllers-connected-with-usb

Please provide the Vendor ID and Product ID of your controller so that we can be certain that it isn't just a controller that hasn't been added to the driver's database yet.

**Comment by FranticRain** [comment]
Okay, so the driver should match to it and macOS sees it. Now let's see if the driver is getting loaded properly. With the controller plugged in, please run `sudo kextload /Library/Extensions/360Controller.kext` in your terminal.

**Comment by Jogium** [comment]
Terminal shows this: /Library/Extensions/360Controller.kext failed to load - (libkern/kext) system policy prevents loading; check the system/kernel logs for errors or try kextutil(8).

**Comment by FranticRain** [comment]
So that's the error that shows up when you've failed to successfully verify the driver in security menu. The button can re-appear if it believes that it was incorrectly pressed. This can often occur due to software that interferes with mouse/pointer input, or with devices that emulate mice/pointers like Wacom tablets. Could you please try to re-enable access to the driver in the security menu using a mouse or trackpad with any sort of modifying software disabled?

**Comment by Jogium** [comment]
Thank you! It was indeed a application for my mouse. When I disabled MagicPrefs, it works! Any way I could donate to you for your effort?
