### ISSUE TITLE
No devices found

### ISSUE THREAD

**Issue by westeis** [360Controller/360Controller#682]
I have a brand new Xbox 360 Wireless Controller. 

I made sure to allow the driver on Security & Privacy and still I got nothing. 

Thanks in advance for your reply! 

![screen shot 2018-05-26 at 23 13 12](https://user-images.githubusercontent.com/39658207/40580204-66365d8a-613a-11e8-8260-5133230f5b6d.png)

**Comment by FranticRain** [comment]
I don't think you meant to close this, but the latest release very clearly says that we do not support wireless Xbox 360 controller on versions of macOS 10.11 or later. This is because Apple made changes to the API that they refuse to fix. There is currently no fix for this, but you can get this to work. If you install an old version of the driver before this feature was removed, you can use a wireless controller with your mac. However, your computer WILL kernel panic whenever the computer goes to sleep. If you go into the preference pane and disable the driver before sleeping the computer, then you will not kernel panic.

I am going to close this issue now because it is a duplicate of other issues.

**Comment by westeis** [comment]
Hi, I'm sorry for that. Yes, I did mean to close the issue because oddly enough, it started to work anyway with this version of the driver. I honestly don't know how.
