### ISSUE TITLE
Macbook not recognising wired Xbox controller

### ISSUE THREAD

**Issue by studsr** [360Controller/360Controller#705]
### Type of Controller
Xbox 360

### OS Version
High Sierra 10.13.5

### Driver Version
0.16.8

### Connection Method
Wired

### Device Name and Info
(If you don't know this information, please refer to the README for how to find it. Enter N/A if not applicable)
>Device Name: None provided
<br/>Product ID: 0x028e
<br/>Vendor ID: 0x045e

### Response of Controller
Green light on the controller flashes for a second.

### Response in Preference Pane
Preference pane says "No controller found"

### Detailed Explaination of Issue
I plug controller in, the green light flashes for a second, so it looks like the Macbook can se et, however your software says "no controller found"

Any help much appreciated, I see others are having similar problems,

Andy.

**Comment by studsr** [comment]
Here's the info you requested Drew.

<img width="749" alt="screen shot 2018-06-25 at 15 15 30" src="https://user-images.githubusercontent.com/40519187/41855570-dfd107b4-788a-11e8-9ad0-7d9e42d0df80.png">

Thanks,

Andy

**Comment by FranticRain** [comment]
I need you to open up your terminal and run `sudo kextload /Library/Extensions/360Controller.kext` and tell me what it says.

If it says `/Library/Extensions/360Controller.kext failed to load - (libkern/kext) system policy prevents loading; check the system/kernel logs for errors or try kextutil(8).` Then you'll need to allow the driver in the `Security & Privacy` section of your `System Preferences`.
![Security and Privacy panel in the macOS System Preferences](https://user-images.githubusercontent.com/33877645/33092253-965b666e-cec7-11e7-940d-3e13b46ca500.png)

Otherwise, this issue will be closed down, because we do not support counterfeit controllers.

**Comment by FranticRain** [comment]
Counterfeit controllers are devices that use the product and vendor IDs of the official Xbox 360 controller in order to try and spoof hardware into recognizing them as official controllers. They are either cheap imitations of the original controller, or unlicensed Chinese hacks. Either way, they violate the USB spec, and therefore cannot be individually supported by the driver.

This issue is being closed due to inactivity.
