### ISSUE TITLE
No Devices found in Xbox 360 tab in System preferences

### ISSUE THREAD

**Issue by PhillipRo** [360Controller/360Controller#741]
Original , Xbox 360

### OS Version
High Sierra - 10.13.5 / Macbook Pro 2012

### Driver Version
360Controller 0.16.8

### Connection Method
Wired

### Device Name and Info

Product ID:	0x028f
Vendor ID:	0x045e  (Microsoft Corporation)
Version:	1.05
Speed:	12 Mb/seg
Location ID:	0x14200000 / 16
Current Available (mA):	500
Current Required (mA):	100
Extra Operating Current (mA):0

### Response of Controller
Lights up

### Response in Preference Pane
No Devices found in Xbox 360 tab in System preferences

### Detailed Explaination of Issue
No Devices found in Xbox 360 tab in System preferences

**Comment by FranticRain** [comment]
Please ensure that the driver has been allowed in System Preferences -> Security and Privacy -> General. This approval UI is only present in the Security & Privacy preferences pane for 30 minutes after the alert. Until you approve the kext, future load attempts will cause the approval UI to reappear but will not trigger another user alert.

![Security and Privacy panel in the macOS System Preferences](https://user-images.githubusercontent.com/33877645/33092253-965b666e-cec7-11e7-940d-3e13b46ca500.png)

**Comment by PhillipRo** [comment]
I already did this, but it still does not work

**Comment by FranticRain** [comment]
I need you to open up your terminal and run `sudo kextload /Library/Extensions/360Controller.kext` and tell me what it says.

**Comment by PhillipRo** [comment]
He asked for the password, I typed and then appeared: Computername:˜user$

**Comment by mmun** [comment]
I'm in a similar situation and I get

```
/Library/Extensions/360Controller.kext failed to load - (libkern/kext) system policy prevents loading; check the system/kernel logs for errors or try kextutil(8).
```

BTW, clicking "Allow" in the screenshot above doesn't seem to do anything.

**Comment by FranticRain** [comment]
@PhillipRo So that means that the driver is being correctly loaded. If you could please try using the controller after running that command, could you tell me if the driver still isn't working for you? All signs point to the driver working fine on your system, and your device is already included in the supported devices, so I'm not sure what the problem is here.

@mmun As stated in the README, "This prompt has been known to have issues with software or hardware that interferes with mouse movement. If you are using software that impacts the movement of your mouse, such as MagicKeys, or are using a special interface device, such as a Wacom tablet, please using a standard input device, such as a mouse, to click this button. This is a security feature of macOS and is out of our control."

**Comment by alexandre-thauvin** [comment]
Hello @FranticRain 
I'm in a similar situation and still no devices found after running kextload (btw no error on this command).

![image](https://user-images.githubusercontent.com/27420929/47084387-ea488e00-d245-11e8-94a6-04ef004b078c.png)

**Comment by FranticRain** [comment]
@alexandre-thauvin Please make a new issue and include your controller product and vendor information.

**Comment by iikas** [comment]
Where can I get the version 360Controller 0.16.8? HELP!! 
already search for many places and nothing

**Comment by FranticRain** [comment]
@iikas Please consult the README for the answer to your query.

**Comment by FranticRain** [comment]
This issue is being closed due to inactivity. We can't fix issues if we don't have enough information. So periodically we close down issues that can't be resolved if they seem to have been abandoned by their creators. If your issue still persists, please open a new issue after thoroughly consulting the README and providing all information as required by the README.
