### ISSUE TITLE
xbox one controller, not finding any devices 

### ISSUE THREAD

**Issue by DxTillett** [360Controller/360Controller#742]
### Type of Controller
Xbox one wireless with wire adapter

### OS Version
high Sierra 10.13.6

### Driver Version 
360Controller 0.16.8

### Connection Method
wireless with a cord adapter

### Device Name and Info
(If you don't know this information, please refer to the README for how to find it. Enter N/A if not applicable)
>Device Name:
<br/>Product ID:0x02FD
<br/>Vendor ID:0x045E

### Response of Controller
it vibrates when I plug it in but does not find in devices found

### Response in Preference Pane
Replace this text with information about the controller's reaction in the preference pane. Does the controller appear in the preference pane? Do all of the buttons, joysticks, and triggers act as expected?

### Detailed Explaination of Issue
I cannot connect my controller to the installer download, no devices are found. I open up the xbox360 controller in system preferences and it does not have any devices found.

**Comment by steph1507** [comment]
+1

**Comment by FranticRain** [comment]
Is this the new adaptive controller? Or some other type of controller? If it's an adaptive, then this may take some more work. Otherwise, I would just like to know why there is a new Xbox One controller, just in case it causes some fresh new issues. Here's a build with the controller added.

[Install360Controller.pkg.zip](https://github.com/360Controller/360Controller/files/2363928/Install360Controller.pkg.zip)

**Comment by d235j** [comment]
Doesn't sound like the adaptive controller (which lacks vibration features)

**Comment by FranticRain** [comment]
@jhkrischel Xbox One controllers are supported via Bluetooth through the operating system. Bluetooth connected Xbox One controllers will not show in the preference pane. They are outside the purview of this driver. If a game doesn't support your controller in Bluetooth mode, it is the responsibility of the game developer to properly support controllers, not ours. Furthermore, wireless is not supported for Xbox One controllers. No one has cracked the obfuscation scheme that Microsoft is using with the wireless adapter.

Looks like this works just fine, still waiting for an adaptive controller to roll around because that is almost certainly going to have a new packet.

**Comment by FranticRain** [comment]
@the-t-in-rtf I'll need the product and vendor IDs as per usual, instructions are in the README. In addition, I'm going to need packet sniffs, as documented here: https://vestigl.com/sniffing/index.html. Except you'll need to document what order you press the buttons and such in. And if you have a device that works with the 3.5mm jacks, getting readings from the furthest left and furthest right inputs should get me everything I need. I don't know how in the world we are going to make it work, but we'll see.

It may require a whole new remapping interface, which I'm not too stoked about. But I want to do my due diligence on making this thing work.

**Comment by FranticRain** [comment]
@the-t-in-rtf Yes, please make a new issue.

**Comment by the-t-in-rtf** [comment]
@FranticRain, [here's the new issue](https://github.com/360Controller/360Controller/issues/753).
