### ISSUE TITLE
Xbox One S controller not properly supported while wireless

### ISSUE THREAD

**Issue by DennisBednarz** [360Controller/360Controller#747]
### Type of Controller
Xbox One S

### OS Version
macOS Mojave 10.14 Beta 10

### Driver Version
0.16.8

### Connection Method
Bluetooth

### Device Name and Info
>Device Name: Xbox Wireless Controler
<br/>Product ID: N/A
<br/>Vendor ID: N/A

### Response of Controller
Controller connects fine and is recognised by macOS but not the driver

### Response in Preference Pane
"No Devices Found"

### Detailed Explaination of Issue
While I know that this driver is not supposed to have support for bluetooth connected Xbox controllers, I believe that's a huge mistake. A lot of macOS games support the Xbox 360 controller EXCLUSIVELY (LEGO Games for example) which means that the Xbox One S controller only works when plugged in via a cable with the 360 spoofing on. Because the device is not recognised while connected via bluetooth, the spoofing cannot be enabled forcing users to use the cable instead. I strongly feel that you (the developer) should reconsider the support.

**Comment by FranticRain** [comment]
The driver exists to provide an interface for Xbox controllers to the operating system. That is what a driver does. In addition to the driver, we built in features to help provide a compatibility layer to try and provide a stopgap solution for games. For the following, keep in mind that I am the person who created the button mapping features and the "Pretend to be a 360 controller" option.

What you are asking is impossible. You are asking for a Bluetooth device to be recognized as a wired Xbox 360 controller. That isn't possible in the macOS kernel. I say this with an asterisk. It may not technically be impossible. It would simply require you the plunge the undocumented depths of the macOS kernel. Apple repeatedly pushes me out of the kernel every time I ask for assistance in interfacing with it. In fact, this driver is one of the best sources of documentation on how to work in Apple's kernel, along with applications like Karabiner, simply because Apple doesn't document and kernel and very much doesn't want you writing applications for it. So, I have no interest in doing this. If someone else would like to undertake this Sisyphean task, they are more than welcome to. But I've considered and reconsidered this and I am not changing my mind.
