### ISSUE TITLE
No Device Found - Xbox 360

### ISSUE THREAD

**Issue by leiigghhh** [360Controller/360Controller#770]
### Type of Controller
Xbox 360

### OS Version
OSX version 10.13.6

### Driver Version
0.16.9

### Connection Method
Wired

### Device Name and Info
>Device Name:USB Gamepad
Product ID:0x5500
Vendor ID:0x12ab (Honey Bee Electronic International Ltd.)

### Response of Controller
Plug in, controller ring lights up for 1 second then turns off

### Response in Preference Pane
No devices found

### Detailed Explaination of Issue
I plug the device in and it's still shown as No devices found. It's supposedly an Xbox 360 controller with the genuine Microsoft sticker (shiny silver one). Unfortunately this specific controller doesn't work. 

I've attempted to add it as a 3rd party controller but after following all the instructions and trying it 3 times I haven't been able to solve this. 

Kind of need the controller to work for my assignment so I'd love some assistance please! 

Cheers

**Comment by FranticRain** [comment]
This device has been added to the driver in 0.16.10. Since this looks like a Chinese knock-off controller, I'll give you the standard warning if it still doesn't work:

This controller is not supported by official Xbox hardware. As such, its support is outside the scope of this driver. We cannot and will not support this controller.
