### ISSUE TITLE
Right trigger not working on fortnite

### ISSUE THREAD

**Issue by mainboy2006** [360Controller/360Controller#771]
### Type of Controller
xbox One

### OS Version
10.13.6

### Driver Version
0.16.9

### Connection Method
Wired

### Device Name and Info
>Device Name:  Controller
<br/>Product ID:  0x02ea
<br/>Vendor ID: 0x045e

### Response of controller
Controller works with everything in fortnite except right trigger, everything works on controller test
### Response in Preference Pane
Everything is fine except that my controller vibrates every time I touch any trigger

### Detailed Explaination of Issue
The right trigger will not work in fortnite. Everything else will.  Also The right trigger will work in the preference pane.  Sry if this is too short of a message but here is not much to explain about this issue

**Comment by FranticRain** [comment]
The driver does not provide any sort of compatibility for individual games beyond what is provided in the preference pane. The driver simply sends button data to the operating system. Once it does that, control is out of the driver's hands. Since Apple does not provide any standardized means of interacting with controllers in macOS, every game uses a different method to read controller data. We cannot provide individual fixes for each game within the controller. That simply isn't feasible. It is the responsibility of game developers to support controllers, not the other way around. We cannot and will not provide support for individual games. If you are using an Xbox One controller, we can recommend that you use the "Pretend to be an Xbox 360 Controller" option in the "Advanced" menu for better game compatibility. Beyond that, there is nothing we can do.
