### ISSUE TITLE
Elite Controller Right Stick Deadzone Issue

### ISSUE THREAD

**Issue by itsfano** [360Controller/360Controller#776]
### Type of Controller
Xbox Elite Controller (Brand New)

### OS Version
Sierra

### Driver Version
0.16.10

### Connection Method
Wired

### Response of Controller
Connects perfectly fine.

### Response in Preference Pane
Everything functions properly in preference pane.

### Detailed Explaination of Issue
While playing Fortnite, the reticle is unresponsive when making minor/precise adjustments near the center with the right stick. These same slight motions register perfectly fine in the preference pane.

Oddly enough, if I enable "Swap Sticks" and try aiming with the left stick, these small movements work perfectly fine in-game.

I've tried spoofing as a 360 controller as well as adjusting the slider in the preference pane to just about every point but continue to get a small deadzone near the center.

**Comment by FranticRain** [comment]
Do you have any means of testing this on an Xbox One console or Windows PC to verify that this is an issue with the driver? This sounds like a hardware issue to me.

**Comment by itsfano** [comment]
Yes this is a brand new controller that works fine on an Xbox. Went out of town and decided to try it on gForce. Like I said, the motions are registered in the 360 Controller panel, just not on fortnite

**Comment by FranticRain** [comment]
The driver does not provide any sort of compatibility for individual games beyond what is provided in the preference pane. The driver simply sends button data to the operating system. Once it does that, control is out of the driver's hands. Since Apple does not provide any standardized means of interacting with controllers in macOS, every game uses a different method to read controller data. We cannot provide individual fixes for each game within the controller. That simply isn't feasible. It is the responsibility of game developers to support controllers, not the other way around. We cannot and will not provide support for individual games. If you are using an Xbox One controller, we can recommend that you use the "Pretend to be an Xbox 360 Controller" option in the "Advanced" menu for better game compatibility. Beyond that, there is nothing we can do.
