### ISSUE TITLE
Controller not recognized

### ISSUE THREAD

**Issue by Lukeade815** [360Controller/360Controller#785]
### Type of Controller
X-Box 360

### OS Version
macOS Mojave 10.14

### Driver Version
Most Recent

### Connection Method
Wireless Adaptor

### Device Name and Info
>Device Name: World of Rock controller

### Response of Controller
All the lights work and do what they're supposed to do, but my computer just isn't recognizing it.

### Response in Preference Pane
Doesn't appear.

### Detailed Explaination of Issue
When I turn on my controller and hold the sync buttons, the lights flash but it says No Devices Found.

**Comment by chriskemm** [comment]
Controller not recognised when connected via USB. (Xbox 360)

OS 10.14

**Comment by FranticRain** [comment]
As of macOS 10.11, Wireless controllers have been unsupported by this driver. This is thanks to a rewrite of the macOS USB kernel. This issue can only be resolved through a rewrite of the driver, which is currently unplanned. Therefore I will be closing this issue, since it is outside the realm of supported devices.
