### ISSUE TITLE
MacBook Pro won't boot up.

### ISSUE THREAD

**Issue by blainedont** [360Controller/360Controller#834]
I have Mojave 10.14.2

I installed your app to make a Xbox controller work.

https://github.com/360Controller/360Controller/releases

Now the MacBook won't boot up after the suggested restart.

**Comment by FranticRain** [comment]
Hold Command + V when you boot the machine. When the text stops moving, take a picture of your screen. That will help us fix this issue more permanently.

Then, in order to fix your machine, you will need to shut it down again, and then hold Command + R to get into recovery mode. From there, open the terminal and run these commands:

```
rm /System/Library/Extensions/360Controller.kext
rm /System/Library/Extensions/Wireless360Controller.kext
rm /System/Library/Extensions/WirelessGamingReceiver.kext
rm /Library/Extensions/360Controller.kext
rm /Library/Extensions/Wireless360Controller.kext
rm /Library/Extensions/WirelessGamingReceiver.kext
rm /Library/Extensions/XboxOneBluetooth.kext
```

You may not have all of these files. This is just the full list to be safe. And one final question, do you know which version of the driver you installed?

**Comment by blainedont** [comment]
It was 0.16.10.

I ended up reinstalling Mojave on the MacBook but I am hesitant to do this
again.  Ultimately I want to use the xbox controller on my mac mini.  Any
tips you recommend?

Richard

**Comment by FranticRain** [comment]
Without your Cmd + V trace, it is impossible to know why you experienced this problem. Without it, I can't promise you anything.

**Comment by blainedont** [comment]
I will attempt the mac mini at some point.  I just need to know if you have
had successful attempts with Mojave.

Richard

**Comment by blainedont** [comment]
Thanks!
