### ISSUE TITLE
Installer is not completing installation

### ISSUE THREAD

**Issue by Sadrat12** [360Controller/360Controller#861]
### Type of Controller
Xbox 360
### OS Version
Mac OS Mojave V. 10.14

### Driver Version
0.16.11 (however have tried other versions and the problem has persisted) 

### Connection Method
N/A 

### Device Name and Info
N/A
### Response of Controller
N/A

### Response in Preference Pane
N/A

### Detailed Explaination of Issue
When I download the driver installer and double click to run it I am prompted to allow access to the developer through systems preferences. Once I have done this the installer opens as expected and I can go through the licence agreement etc as normal. It skips the 'destination selection' and immediately jumps to 'Installation type'. Here, whilst the 'go back' button works as intended, the 'install' button does nothing. So I can not get past the screen below.
![Screenshot 2019-04-08 at 15 28 13](https://user-images.githubusercontent.com/49415581/55754740-f9e5aa00-5a12-11e9-9bbf-29cc2255c266.png)

**Comment by FranticRain** [comment]
Skipping the "Destination Select" step is normal, because kexts and preference panes can only be installed in one location.

The installation button should create a popup that prompts for administrator privileges. Are you missing it, or do you not have administrator rights on your machine?

**Comment by FranticRain** [comment]
This issue is being closed due to inactivity. We can't fix issues if we don't have enough information. So periodically we close down issues that can't be resolved if they seem to have been abandoned by their creators. If your issue still persists, please open a new issue after thoroughly consulting the README and providing all information as required by the README.
