### ISSUE TITLE
Razer Onza not detected

### ISSUE THREAD

**Issue by lisasbrandy** [360Controller/360Controller#878]
### Type of Controller
Xbox 360

### OS Version
Mojave

### Driver Version
Version 1.0.0-alpha.2

### Connection Method
Wired

### Device Name and Info
(If you don't know this information, please refer to the README for how to find it. Enter N/A if not applicable)
>Device Name: 
<br/>Product ID: 0xfd00
<br/>Vendor ID: 0x1bad

### Response of Controller
Controller lights up X,A,b,y and 3

### Response in Preference Pane
Nothing responds. Says no devices found

### Detailed Explaination of Issue
The computer does not respond to anything from the controller in any situation including games and the system preferences pane.

**Comment by FranticRain** [comment]
This issue is being closed due to inactivity. We can't fix issues if we don't have enough information. So periodically we close down issues that can't be resolved if they seem to have been abandoned by their creators. If your issue still persists, please open a new issue after thoroughly consulting the README and providing all information as required by the README.
