### ISSUE TITLE
Xbox One controller not found on Mac OS Mojave 10.14.5

### ISSUE THREAD

**Issue by ashrod98** [360Controller/360Controller#911]
### Type of Controller
Xbox One

### OS Version
MacOS Mojave 10.14.5

### Driver Version
360Controller 1.0.0 alpha.3

### Connection Method
Wired

### Device Name and Info
(If you don't know this information, please refer to the README for how to find it. Enter N/A if not applicable)
>Device Name: Controller
<br/>Product ID: 0x02dd
<br/>Vendor ID: 0x045e  (Microsoft Corporation)

### Response of Controller
Vibrates for a moment immediately after connecting it to my mac. There are no lights nor other indicator that it is connected other than the fact that it shows up under USB devices in my system report.

### Response in Preference Pane
Preference Pane does not list my device. The only item in the drop-down menu is No Devices Found.

### Detailed Explanation of Issue
I recently downloaded and installed the most recent driver (alpha 3) onto my mac. Twice, just in case something went wrong. When I connect my controller via micro USB cable to my mac and it vibrates for just a second, but the controller never shows up in system preferences. It does appear as a USB device on my system report. This is the name of the file from which I installed the driver: 360ControllerInstall_1.0.0-alpha.3 16-59-42-537.dmg (Got this from my trash.)

<img width="660" alt="Screen Shot 2019-06-28 at 5 11 20 PM" src="https://user-images.githubusercontent.com/52333945/60371610-c7bb6700-99c7-11e9-8625-89995af13b29.png">

**Comment by FranticRain** [comment]
Can you go into your terminal and run this command, and let me know what the system says?
```
sudo kextutil /Library/Extensions/360Controller.kext
```

**Comment by kevzettler** [comment]
@FranticRain I have the same setup as @ashrod98 heres my terminal output

```
$ sudo kextutil /Library/Extensions/360Controller.kext
Notice: /Library/Extensions/360Controller.kext has debug properties set.
Kext rejected due to system policy: <OSKext 0x7fddf8d045c0 [0x7fff8dcd08f0]> { URL = "file:///Library/StagedExtensions/Library/Extensions/360Controller.kext/", ID = "com.mice.driver.Xbox360Controller" }
Kext rejected due to system policy: <OSKext 0x7fddf8d045c0 [0x7fff8dcd08f0]> { URL = "file:///Library/StagedExtensions/Library/Extensions/360Controller.kext/", ID = "com.mice.driver.Xbox360Controller" }
Diagnostics for /Library/Extensions/360Controller.kext:
Warnings:
    Personality CFBundleIdentifier differs from containing kext's (not necessarily a mistake, but rarely done):
        ChatPadKeyboardEvents
```

**Comment by FranticRain** [comment]
@kevzettler Please ensure that the driver has been allowed in System Preferences -> Security and Privacy -> General. This approval UI prompt is only present in the Security & Privacy preferences pane for 30 minutes after an alert, such as the one that appeared during installation. Until you approve the kext, future load attempts will cause the approval UI to reappear but will not trigger another user alert. You can trigger a kext load by either re-connecting the controller or by running

```sudo kextutil /Library/Extensions/360Controller.kext```

The approval UI is as follows:

![Security and Privacy panel in the macOS System Preferences](https://user-images.githubusercontent.com/33877645/33092253-965b666e-cec7-11e7-940d-3e13b46ca500.png)

**Comment by kevzettler** [comment]
Thanks @FranticRain that resolved the issue for me. Controller is now detected

**Comment by FranticRain** [comment]
@kevzettler Apple, in their infinite wisdom, decided to only show the prompt once for any developer. So if you've ever tried to load any software and missed the prompt even once, then you'll never see a pop-up ever again. Just this little "allow" button in your system preferences. It wouldn't surprise me if it just got covered up or missed the one time it showed up and then you just never got a chance to see it ever again.

**Comment by ashrod98** [comment]
Thanks! It works for me as well

**Comment by kawaiicute** [comment]
<img width="663" alt="Screenshot 2019-07-04 at 20 27 14" src="https://user-images.githubusercontent.com/52547020/60685301-3bfb7c00-9e9a-11e9-9ca1-cf4057e95981.png">


i have this

**Comment by chumbaker** [comment]
> Can you go into your terminal and run this command, and let me know what the system says?
> 
> ```
> sudo kextutil /Library/Extensions/360Controller.kext
> ```

Hi! First post here, so sorry if this isn't the right etiquette.
I'm also running 10.14.5, and having the same issues as op. However, when I put that command into terminal, it gave me this:

Error copying bundle during staging: -1
Unable to stage kext (/System/Library/Extensions/roller.kext) to secure location.
Notice: /Library/Extensions/360Controller.kext has debug properties set.
Warnings: 
    Personality CFBundleIdentifier differs from containing kext's (not necessarily a mistake, but rarely done): 
        ChatPadKeyboardEvents
      
It's not my controller, laptop, or cord, and I already allowed the program to make changes. I'm really at a loss here :-(

**Comment by itskando** [comment]
> When I put that command into terminal, it gave me this:
> 
> Error copying bundle during staging: -1
> Unable to stage kext (/System/Library/Extensions/roller.kext) to secure location.
> Notice: /Library/Extensions/360Controller.kext has debug properties set.
> Warnings:
> Personality CFBundleIdentifier differs from containing kext's (not necessarily a mistake, but rarely done):
> ChatPadKeyboardEvents

+1

**Comment by DanSpicyTaco** [comment]
> when I put that command into terminal, it gave me this:
> 
> Error copying bundle during staging: -1
> Unable to stage kext (/System/Library/Extensions/roller.kext) to secure location.
> Notice: /Library/Extensions/360Controller.kext has debug properties set.
> Warnings:
> Personality CFBundleIdentifier differs from containing kext's (not necessarily a mistake, but rarely done):
> ChatPadKeyboardEvents

I had the same issue and Fixed it by clearing the kextcache:
`sudo kextcache --clear-staging`

And then running the command again:
`sudo kextutil /Library/Extensions/360Controller.kext`

The output for that was:
`Error copying bundle during staging: -1
Unable to stage kext (/System/Library/Extensions/roller.kext) to secure location.
kext file:///Library/StagedExtensions/System/Library/Extensions/1085F424-AEF4-41D6-85F1-EB2ECC7843.kext/ is in hash exception list, allowing to load
kext file:///Library/StagedExtensions/System/Library/Extensions/8A667711-5478-489B-A6A2-777DCDB1BB.kext/ is in hash exception list, allowing to load
Notice: /Library/Extensions/360Controller.kext has debug properties set.
Warnings: 
    Personality CFBundleIdentifier differs from containing kext's (not necessarily a mistake, but rarely done): 
        ChatPadKeyboardEvents`

Then, I unplugged the controller and inserted it again and it seems to work now! (I'm not entirely sure why though, but it worked for me)

**Type of Controller**
Xbox One (Wired)

**OS Version**
MacOS Mojave 10.14.5

**Driver Version**
360Controller 1.0.0 alpha.3

**Comment by romansand** [comment]
Hey guys,

I have the same issue.
MacOS isn't detecting a xbox controller.

The output of:
`sudo kextutil /Library/Extensions/360Controller.kext`
Is
`Error copying bundle during staging: -1
Unable to stage kext (/System/Library/Extensions/roller.kext) to secure location.
Notice: /Library/Extensions/360Controller.kext has debug properties set.
Warnings: 
    Personality CFBundleIdentifier differs from containing kext's (not necessarily a mistake, but rarely done): 
        ChatPadKeyboardEvents`

I've tried alpha.2 and alpha.3 versions, but it didn't prompt a Security approval during the installation.
Any ideas/suggestions?

**Type of Controller**
Xbox One (Wired)

**OS Version**
MacOS Mojave 10.14.5

**Driver Version**
360Controller 1.0.0 alpha.3

**Comment by coal** [comment]
Same issue as above.

CMP:~ coal$ sudo kextutil /Library/Extensions/360Controller.kext
Error copying bundle during staging: -1
Unable to stage kext (/System/Library/Extensions/roller.kext) to secure location.
Notice: /Library/Extensions/360Controller.kext has debug properties set.
Warnings: 
    Personality CFBundleIdentifier differs from containing kext's (not necessarily a mistake, but rarely done): 
        ChatPadKeyboardEvents

CMP:~ coal$ sudo kextutil /Library/Extensions/360Controller.kext
Error copying bundle during staging: -1
Unable to stage kext (/System/Library/Extensions/roller.kext) to secure location.
Notice: /Library/Extensions/360Controller.kext has debug properties set.
Warnings: 
    Personality CFBundleIdentifier differs from containing kext's (not necessarily a mistake, but rarely done): 
        ChatPadKeyboardEvents


Type of Controller
Xbox One (Wireless)

OS Version
MacOS Mojave 10.14.5

Driver Version
360Controller 1.0.0 alpha.3

**Comment by bamode** [comment]
I have the same issue and OS version as Coal above. Can confirm that the exact same issue and output from kextutil exists for wired Xbox One controller. Mojave 10.14.6 contained an update to the USB drivers that is probably the root cause of the issue. Running kextutil at maximum verbosity confirms that the machine seems to believe that the kext is loaded successfully, though it clearly is not. Full output reproduced below.

`Kext user-space log filter changed from 0xff2 to 0xfff.
Kext kernel-space log filter changed from 0xff2 to 0xfff.
Kext library architecture set to x86_64.
Can't stat /AppleInternal - No such file or directory.
Defaulting to kernel file '/System/Library/Kernels/kernel'
Kext library recording diagnostics for: validation authentication dependencies warnings.
Error copying bundle during staging: -1
Unable to stage kext (/System/Library/Extensions/roller.kext) to secure location.
Notice: /Library/Extensions/360Controller.kext has debug properties set.
Reading loaded kext info from kernel.
(kernel) User-space log flags changed from 0x0 to 0xfff.
(kernel) Received 'Get Loaded Kext Info' request from user space.
(kernel) Returning loaded kext info.
Loaded kext info:
{
}

Warnings:
    Personality CFBundleIdentifier differs from containing kext's (not necessarily a mistake, but rarely done):
        ChatPadKeyboardEvents

/Library/Extensions/360Controller.kext appears to be loadable (not including linkage for on-disk libraries).
Reading loaded kext info from kernel.
(kernel) User-space log flags changed from 0x0 to 0xfff.
(kernel) Received 'Get Loaded Kext Info' request from user space.
(kernel) Returning loaded kext info.
Loaded kext info:
{
}

Loading /Library/Extensions/360Controller.kext.
Reading load info for 15 kexts.
Reading loaded kext info from kernel.
(kernel) User-space log flags changed from 0x0 to 0xfff.
(kernel) Received 'Get Loaded Kext Info' request from user space.
(kernel) Returning loaded kext info.
Loaded kext info:
{
"com.apple.kpi.bsd" = {
    "OSBundleWiredSize" = 40528
    "CFBundleIdentifier" = "com.apple.kpi.bsd"
    "OSBundleUUID" = <4e953e56 65c84d2e 94e10727 512d23a2>
    "OSBundleLoadAddress" = -551890714624
    "OSBundleLoadTag" = 1
    "OSBundleStarted" = true
    "OSBundleCompatibleVersion" = "8.0.0b1"
    "OSKernelResource" = true
    "CFBundleVersion" = "18.7.0"
    "OSBundlePath" =
        "/System/Library/Extensions/System.kext/PlugIns/BSDKernel.kext"
    "OSBundleRetainCount" = 109
    "OSBundlePrelinked" = true
    "OSBundleIsInterface" = true
    "OSBundleLoadSize" = 40528
}
"com.apple.iokit.IOPCIFamily" = {
    "OSBundleWiredSize" = 221184
    "CFBundleIdentifier" = "com.apple.iokit.IOPCIFamily"
    "OSBundleStarted" = true
    "OSBundleCPUType" = 16777223
    "OSBundleCompatibleVersion" = "1.0.0b1"
    "OSBundleUUID" = <202f4f5c 5e3c35a9 a7adf85b 0e3cd199>
    "OSKernelResource" = false
    "CFBundleVersion" = "2.9"
    "OSBundleLoadTag" = 13
    "OSBundleLoadAddress" = -551890104320
    "OSBundleDependencies" = (
        5
        6
        3
        8
        7
    )
    "OSBundlePath" = "/System/Library/Extensions/IOPCIFamily.kext"
    "OSBundleRetainCount" = 39
    "OSBundleCPUSubtype" = 3
    "OSBundlePrelinked" = true
    "OSBundleIsInterface" = false
    "OSBundleLoadSize" = 221184
}
"com.apple.kpi.dsep" = {
    "OSBundleWiredSize" = 14592
    "CFBundleIdentifier" = "com.apple.kpi.dsep"
    "OSBundleUUID" = <9a7e5471 f6494a5a b0ce1bd3 aa836de3>
    "OSBundleLoadAddress" = -551883202560
    "OSBundleLoadTag" = 2
    "OSBundleStarted" = true
    "OSBundleCompatibleVersion" = "8.0.0b1"
    "OSKernelResource" = true
    "CFBundleVersion" = "18.7.0"
    "OSBundlePath" =
        "/System/Library/Extensions/System.kext/PlugIns/MACFramework.kext"
    "OSBundleRetainCount" = 10
    "OSBundlePrelinked" = true
    "OSBundleIsInterface" = true
    "OSBundleLoadSize" = 14592
}
"com.apple.driver.AppleBusPowerController" = {
    "OSBundleWiredSize" = 32768
    "CFBundleIdentifier" = "com.apple.driver.AppleBusPowerController"
    "OSBundleStarted" = true
    "OSBundleCPUType" = 16777223
    "OSBundleCompatibleVersion" = "1.0"
    "OSBundleUUID" = <3af293c0 2a5d3eb2 85189f09 6e1b9198>
    "OSKernelResource" = false
    "CFBundleVersion" = "1.0"
    "OSBundleLoadTag" = 16
    "OSBundleLoadAddress" = -551887818752
    "OSBundleDependencies" = (
        5
        12
        3
        14
        7
        6
    )
    "OSBundlePath" = "/System/Library/Extensions/AppleBusPowerController.kext"
    "OSBundleRetainCount" = 1
    "OSBundleCPUSubtype" = 3
    "OSBundlePrelinked" = true
    "OSBundleIsInterface" = false
    "OSBundleLoadSize" = 32768
}
"com.apple.kpi.unsupported" = {
    "OSBundleWiredSize" = 24272
    "CFBundleIdentifier" = "com.apple.kpi.unsupported"
    "OSBundleUUID" = <58f88617 83344a54 b5db9bb7 45504cb5>
    "OSBundleLoadAddress" = -551890128896
    "OSBundleLoadTag" = 8
    "OSBundleStarted" = true
    "OSBundleCompatibleVersion" = "8.0.0b1"
    "OSKernelResource" = true
    "CFBundleVersion" = "18.7.0"
    "OSBundlePath" =
        "/System/Library/Extensions/System.kext/PlugIns/Unsupported.kext"
    "OSBundleRetainCount" = 83
    "OSBundlePrelinked" = true
    "OSBundleIsInterface" = true
    "OSBundleLoadSize" = 24272
}
"com.apple.driver.AppleSMC" = {
    "OSBundleWiredSize" = 122880
    "CFBundleIdentifier" = "com.apple.driver.AppleSMC"
    "OSBundleStarted" = true
    "OSBundleCPUType" = 16777223
    "OSBundleCompatibleVersion" = "1.0.1d1"
    "OSBundleUUID" = <0a338aa2 4958384b 994159a9 6a38c42c>
    "OSKernelResource" = false
    "CFBundleVersion" = "3.1.9"
    "OSBundleLoadTag" = 14
    "OSBundleLoadAddress" = -551887949824
    "OSBundleDependencies" = (
        7
        8
        13
        3
        12
        6
        5
        1
    )
    "OSBundlePath" = "/System/Library/Extensions/AppleSMC.kext"
    "OSBundleRetainCount" = 9
    "OSBundleCPUSubtype" = 3
    "OSBundlePrelinked" = true
    "OSBundleIsInterface" = false
    "OSBundleLoadSize" = 122880
}
"com.apple.iokit.IOUSBHostFamily" = {
    "OSBundleWiredSize" = 499712
    "CFBundleIdentifier" = "com.apple.iokit.IOUSBHostFamily"
    "OSBundleStarted" = true
    "OSBundleCPUType" = 16777223
    "OSBundleCompatibleVersion" = "1.0.1"
    "OSBundleUUID" = <bd06015a 414d34df be367b90 34d7360d>
    "OSKernelResource" = false
    "CFBundleVersion" = "1.2"
    "OSBundleLoadTag" = 18
    "OSBundleLoadAddress" = -551887753216
    "OSBundleDependencies" = (
        17
        7
        8
        3
        1
        16
        5
        6
    )
    "OSBundlePath" = "/System/Library/Extensions/IOUSBHostFamily.kext"
    "OSBundleRetainCount" = 15
    "OSBundleCPUSubtype" = 3
    "OSBundlePrelinked" = true
    "OSBundleIsInterface" = false
    "OSBundleLoadSize" = 499712
}
"com.apple.iokit.IOACPIFamily" = {
    "OSBundleWiredSize" = 36864
    "CFBundleIdentifier" = "com.apple.iokit.IOACPIFamily"
    "OSBundleStarted" = true
    "OSBundleCPUType" = 16777223
    "OSBundleCompatibleVersion" = "1.0.0d1"
    "OSBundleUUID" = <3e8e9870 2e4133f6 acbf35dd c08f22b5>
    "OSKernelResource" = false
    "CFBundleVersion" = "1.4"
    "OSBundleLoadTag" = 12
    "OSBundleLoadAddress" = -551887986688
    "OSBundleDependencies" = (
        7
        5
        3
        8
    )
    "OSBundlePath" = "/System/Library/Extensions/IOACPIFamily.kext"
    "OSBundleRetainCount" = 29
    "OSBundleCPUSubtype" = 3
    "OSBundlePrelinked" = true
    "OSBundleIsInterface" = false
    "OSBundleLoadSize" = 36864
}
"com.apple.kpi.iokit" = {
    "OSBundleWiredSize" = 138208
    "CFBundleIdentifier" = "com.apple.kpi.iokit"
    "OSBundleUUID" = <d04a4466 0cf142e3 adbc158b fc96221d>
    "OSBundleLoadAddress" = -551890542592
    "OSBundleLoadTag" = 3
    "OSBundleStarted" = true
    "OSBundleCompatibleVersion" = "7.0"
    "OSKernelResource" = true
    "CFBundleVersion" = "18.7.0"
    "OSBundlePath" =
        "/System/Library/Extensions/System.kext/PlugIns/IOKit.kext"
    "OSBundleRetainCount" = 137
    "OSBundlePrelinked" = true
    "OSBundleIsInterface" = true
    "OSBundleLoadSize" = 138208
}
"com.apple.kpi.mach" = {
    "OSBundleWiredSize" = 16224
    "CFBundleIdentifier" = "com.apple.kpi.mach"
    "OSBundleUUID" = <a3c5492d e36345fd 98e779ba 94757f69>
    "OSBundleLoadAddress" = -551890616320
    "OSBundleLoadTag" = 6
    "OSBundleStarted" = true
    "OSBundleCompatibleVersion" = "8.0.0d0"
    "OSKernelResource" = true
    "CFBundleVersion" = "18.7.0"
    "OSBundlePath" = "/System/Library/Extensions/System.kext/PlugIns/Mach.kext"
    "OSBundleRetainCount" = 129
    "OSBundlePrelinked" = true
    "OSBundleIsInterface" = true
    "OSBundleLoadSize" = 16224
}
"com.apple.kpi.private" = {
    "OSBundleWiredSize" = 54992
    "CFBundleIdentifier" = "com.apple.kpi.private"
    "OSBundleUUID" = <4575d726 4a884c68 97258b51 80ea19d6>
    "OSBundleLoadAddress" = -551890599936
    "OSBundleLoadTag" = 7
    "OSBundleStarted" = true
    "OSBundleCompatibleVersion" = "8.0.0b1"
    "OSKernelResource" = true
    "CFBundleVersion" = "18.7.0"
    "OSBundlePath" =
        "/System/Library/Extensions/System.kext/PlugIns/Private.kext"
    "OSBundleRetainCount" = 81
    "OSBundlePrelinked" = true
    "OSBundleIsInterface" = true
    "OSBundleLoadSize" = 54992
}
"com.apple.driver.usb.AppleUSBCommon" = {
    "OSBundleWiredSize" = 32768
    "CFBundleIdentifier" = "com.apple.driver.usb.AppleUSBCommon"
    "OSBundleStarted" = true
    "OSBundleCPUType" = 16777223
    "OSBundleCompatibleVersion" = "1.0"
    "OSBundleUUID" = <fa45971b 83c43569 901e749a 36177c94>
    "OSKernelResource" = false
    "CFBundleVersion" = "1.0"
    "OSBundleLoadTag" = 17
    "OSBundleLoadAddress" = -551887785984
    "OSBundleDependencies" = (
        1
        5
        3
        6
    )
    "OSBundlePath" = "/System/Library/Extensions/AppleUSBCommon.kext"
    "OSBundleRetainCount" = 5
    "OSBundleCPUSubtype" = 3
    "OSBundlePrelinked" = true
    "OSBundleIsInterface" = false
    "OSBundleLoadSize" = 32768
}
"com.apple.iokit.IOHIDFamily" = {
    "OSBundleWiredSize" = 520192
    "CFBundleIdentifier" = "com.apple.iokit.IOHIDFamily"
    "OSBundleStarted" = true
    "OSBundleCPUType" = 16777223
    "OSBundleCompatibleVersion" = "1.0.0b1"
    "OSBundleUUID" = <4d861da4 fe3a3d9d 8123038e 9fbfe182>
    "OSKernelResource" = false
    "CFBundleVersion" = "2.0.0"
    "OSBundleLoadTag" = 45
    "OSBundleLoadAddress" = -551881957376
    "OSBundleDependencies" = (
        7
        8
        3
        1
        5
        6
        2
    )
    "OSBundlePath" = "/System/Library/Extensions/IOHIDFamily.kext"
    "OSBundleRetainCount" = 10
    "OSBundleCPUSubtype" = 3
    "OSBundlePrelinked" = true
    "OSBundleIsInterface" = false
    "OSBundleLoadSize" = 520192
}
"com.apple.kpi.libkern" = {
    "OSBundleWiredSize" = 54592
    "CFBundleIdentifier" = "com.apple.kpi.libkern"
    "OSBundleUUID" = <c17cbc31 d42f4462 a3eb8ec7 75d6b652>
    "OSBundleLoadAddress" = -551890673664
    "OSBundleLoadTag" = 5
    "OSBundleStarted" = true
    "OSBundleCompatibleVersion" = "8.0.0d0"
    "OSKernelResource" = true
    "CFBundleVersion" = "18.7.0"
    "OSBundlePath" =
        "/System/Library/Extensions/System.kext/PlugIns/Libkern.kext"
    "OSBundleRetainCount" = 144
    "OSBundlePrelinked" = true
    "OSBundleIsInterface" = true
    "OSBundleLoadSize" = 54592
}
}

/System/Library/Extensions/IOHIDFamily.kext (version 2.0, UUID 4D861DA4-FE3A-3D9D-8123-038E9FBFE182) is loaded.
/System/Library/Extensions/IOHIDFamily.kext (version 2.0): is started.
setting load address of /System/Library/Extensions/IOHIDFamily.kext to 0xffffff7f8145a000
/System/Library/Extensions/System.kext/PlugIns/Mach.kext (version 18.7, UUID A3C5492D-E363-45FD-98E7-79BA94757F69) is loaded.
/System/Library/Extensions/System.kext/PlugIns/Mach.kext (version 18.7): is started.
setting load address of /System/Library/Extensions/System.kext/PlugIns/Mach.kext to 0xffffff7f80c18000
/System/Library/Extensions/IOUSBHostFamily.kext (version 1.2, UUID BD06015A-414D-34DF-BE36-7B9034D7360D) is loaded.
/System/Library/Extensions/IOUSBHostFamily.kext (version 1.2): is started.
setting load address of /System/Library/Extensions/IOUSBHostFamily.kext to 0xffffff7f80ed3000
/System/Library/Extensions/System.kext/PlugIns/IOKit.kext (version 18.7, UUID D04A4466-0CF1-42E3-ADBC-158BFC96221D) is loaded.
/System/Library/Extensions/System.kext/PlugIns/IOKit.kext (version 18.7): is started.
setting load address of /System/Library/Extensions/System.kext/PlugIns/IOKit.kext to 0xffffff7f80c2a000
/System/Library/Extensions/System.kext/PlugIns/Libkern.kext (version 18.7, UUID C17CBC31-D42F-4462-A3EB-8EC775D6B652) is loaded.
/System/Library/Extensions/System.kext/PlugIns/Libkern.kext (version 18.7): is started.
setting load address of /System/Library/Extensions/System.kext/PlugIns/Libkern.kext to 0xffffff7f80c0a000
/System/Library/Extensions/System.kext/PlugIns/BSDKernel.kext (version 18.7, UUID 4E953E56-65C8-4D2E-94E1-0727512D23A2) is loaded.
/System/Library/Extensions/System.kext/PlugIns/BSDKernel.kext (version 18.7): is started.
setting load address of /System/Library/Extensions/System.kext/PlugIns/BSDKernel.kext to 0xffffff7f80c00000
/System/Library/Extensions/System.kext/PlugIns/MACFramework.kext (version 18.7, UUID 9A7E5471-F649-4A5A-B0CE-1BD3AA836DE3) is loaded.
/System/Library/Extensions/System.kext/PlugIns/MACFramework.kext (version 18.7): is started.
setting load address of /System/Library/Extensions/System.kext/PlugIns/MACFramework.kext to 0xffffff7f8132a000
/System/Library/Extensions/System.kext/PlugIns/Unsupported.kext (version 18.7, UUID 58F88617-8334-4A54-B5DB-9BB745504CB5) is loaded.
/System/Library/Extensions/System.kext/PlugIns/Unsupported.kext (version 18.7): is started.
setting load address of /System/Library/Extensions/System.kext/PlugIns/Unsupported.kext to 0xffffff7f80c8f000
/System/Library/Extensions/System.kext/PlugIns/Private.kext (version 18.7, UUID 4575D726-4A88-4C68-9725-8B5180EA19D6) is loaded.
/System/Library/Extensions/System.kext/PlugIns/Private.kext (version 18.7): is started.
setting load address of /System/Library/Extensions/System.kext/PlugIns/Private.kext to 0xffffff7f80c1c000
/System/Library/Extensions/AppleBusPowerController.kext (version 1.0, UUID 3AF293C0-2A5D-3EB2-8518-9F096E1B9198) is loaded.
/System/Library/Extensions/AppleBusPowerController.kext (version 1.0): is started.
setting load address of /System/Library/Extensions/AppleBusPowerController.kext to 0xffffff7f80ec3000
/System/Library/Extensions/AppleUSBCommon.kext (version 1.0, UUID FA45971B-83C4-3569-901E-749A36177C94) is loaded.
/System/Library/Extensions/AppleUSBCommon.kext (version 1.0): is started.
setting load address of /System/Library/Extensions/AppleUSBCommon.kext to 0xffffff7f80ecb000
/System/Library/Extensions/AppleSMC.kext (version 3.1.9, UUID 0A338AA2-4958-384B-9941-59A96A38C42C) is loaded.
/System/Library/Extensions/AppleSMC.kext (version 3.1.9): is started.
setting load address of /System/Library/Extensions/AppleSMC.kext to 0xffffff7f80ea3000
/System/Library/Extensions/IOACPIFamily.kext (version 1.4, UUID 3E8E9870-2E41-33F6-ACBF-35DDC08F22B5) is loaded.
/System/Library/Extensions/IOACPIFamily.kext (version 1.4): is started.
setting load address of /System/Library/Extensions/IOACPIFamily.kext to 0xffffff7f80e9a000
/System/Library/Extensions/IOPCIFamily.kext (version 2.9, UUID 202F4F5C-5E3C-35A9-A7AD-F85B0E3CD199) is loaded.
/System/Library/Extensions/IOPCIFamily.kext (version 2.9): is started.
setting load address of /System/Library/Extensions/IOPCIFamily.kext to 0xffffff7f80c95000
Omitting loaded kext /System/Library/Extensions/System.kext/PlugIns/MACFramework.kext from mkext for kernel load.
Omitting loaded kext /System/Library/Extensions/System.kext/PlugIns/Mach.kext from mkext for kernel load.
Omitting loaded kext /System/Library/Extensions/System.kext/PlugIns/Libkern.kext from mkext for kernel load.
Omitting loaded kext /System/Library/Extensions/System.kext/PlugIns/BSDKernel.kext from mkext for kernel load.
Omitting loaded kext /System/Library/Extensions/System.kext/PlugIns/IOKit.kext from mkext for kernel load.
Omitting loaded kext /System/Library/Extensions/System.kext/PlugIns/Unsupported.kext from mkext for kernel load.
Omitting loaded kext /System/Library/Extensions/System.kext/PlugIns/Private.kext from mkext for kernel load.
Omitting loaded kext /System/Library/Extensions/IOHIDFamily.kext from mkext for kernel load.
Omitting loaded kext /System/Library/Extensions/IOACPIFamily.kext from mkext for kernel load.
Omitting loaded kext /System/Library/Extensions/IOPCIFamily.kext from mkext for kernel load.
Omitting loaded kext /System/Library/Extensions/AppleSMC.kext from mkext for kernel load.
Omitting loaded kext /System/Library/Extensions/AppleBusPowerController.kext from mkext for kernel load.
Omitting loaded kext /System/Library/Extensions/AppleUSBCommon.kext from mkext for kernel load.
Omitting loaded kext /System/Library/Extensions/IOUSBHostFamily.kext from mkext for kernel load.
KextAudit initialized: audit=T
KextAudit didn't find a bridge: audit=F
Adding /Library/StagedExtensions/Library/Extensions/360Controller.kext to mkext.
/Library/StagedExtensions/Library/Extensions/360Controller.kext added 147840-byte noncompressed executable to mkext.
Created mkext for architecture x86_64 containing 1 kexts.
Loading /Library/StagedExtensions/Library/Extensions/360Controller.kext.
(kernel) User-space log flags changed from 0x0 to 0xfff.
(kernel) Received kext load request from user space.
(kernel) Received request from user space to load kext com.mice.driver.Xbox360Controller.
(kernel) Loading kext com.mice.driver.Xbox360Controller.
(kernel) Kext com.apple.iokit.IOHIDFamily is already loaded.
(kernel) Kext com.apple.iokit.IOHIDFamily sending 4 personalities to the IOCatalogue and starting matching.
(kernel) Kext com.apple.kpi.mach is already loaded.
(kernel) Kext com.apple.iokit.IOUSBHostFamily is already loaded.
(kernel) Kext com.apple.iokit.IOUSBHostFamily sending 34 personalities to the IOCatalogue and starting matching.
(kernel) Kext com.apple.kpi.iokit is already loaded.
(kernel) Kext com.apple.kpi.libkern is already loaded.
(kernel) Kext com.apple.kpi.bsd is already loaded.
(kernel) Allocated link buffer for kext com.mice.driver.Xbox360Controller at 0xffffff7f88419000 (90112 bytes).
(kernel) Kext com.mice.driver.Xbox360Controller executable loaded; 22 pages at 0xffffff7f83c19000 (load tag 174).
(kernel) Kext com.mice.driver.Xbox360Controller calling module start function.
(kernel) Kext com.mice.driver.Xbox360Controller registered class ChatPadKeyboardClass.
(kernel) Kext com.mice.driver.Xbox360Controller has IOService subclass ChatPadKeyboardClass; enabling autounload.
(kernel) Kext com.mice.driver.Xbox360Controller registered class Xbox360Peripheral.
(kernel) Kext com.mice.driver.Xbox360Controller registered class Xbox360ControllerClass.
(kernel) Kext com.mice.driver.Xbox360Controller registered class Xbox360Pretend360Class.
(kernel) Kext com.mice.driver.Xbox360Controller registered class XboxOriginalControllerClass.
(kernel) Kext com.mice.driver.Xbox360Controller registered class XboxOneControllerClass.
(kernel) Kext com.mice.driver.Xbox360Controller registered class XboxOnePretend360Class.
(kernel) Kext com.mice.driver.Xbox360Controller is now started.
(kernel) Kext com.mice.driver.Xbox360Controller sending 221 personalities to the IOCatalogue and starting matching.
(kernel) Kext com.mice.driver.Xbox360Controller loaded.
Successfully loaded /Library/StagedExtensions/Library/Extensions/360Controller.kext.
/Library/Extensions/360Controller.kext successfully loaded (or already loaded).`

**Comment by heran99** [comment]
+1 same problem here:

> Error copying bundle during staging: -1
> Unable to stage kext (/System/Library/Extensions/roller.kext) to secure location.
> Notice: /Library/Extensions/360Controller.kext has debug properties set.
> Warnings: 
>     Personality CFBundleIdentifier differs from containing kext's (not necessarily a mistake, but rarely done): 
>         ChatPadKeyboardEvents


**Type of Controller**
Xbox One (Wireless)

**OS Version**
MacOS Mojave 10.14.6

**Driver Version**
360Controller 1.0.0 alpha.3

**Comment by drizzylga1151** [comment]
Notice: /Library/Extensions/360Controller.kext has debug properties set.
Can't open CFBundle for /System/Library/Extensions/roller.kext.
Can't create kext from cache: /System/Library/Extensions/roller.kext is already open and has a different CFBundleIdentifier from identifier->path cache entry 0.
Can't create kext from cache: /System/Library/Extensions/roller.kext is already open and has a different CFBundleIdentifier from identifier->path cache entry 0.
Kext with invalid signatured (-67054) allowed: <OSKext 0x7f9a28442bc0 [0x7fffa9dc18e0]> { URL = "file:///System/Library/Extensions/IOUSBHostFamily.kext/", ID = "com.apple.iokit.IOUSBHostFamily" }
Warnings: 
    Personality CFBundleIdentifier differs from containing kext's (not necessarily a mistake, but rarely done): 
        ChatPadKeyboardEvents

Can't create kext from cache: /System/Library/Extensions/roller.kext is already open and has a different CFBundleIdentifier from identifier->path cache entry 0.

**Comment by FranticRain** [comment]
Okay, this issue is a mess of random garbage that I can't individually address. If any of you still have an issue, please make a new issue following the template and include the output from kextutil.

**Comment by vrdevelopersco** [comment]
seems doing

`sudo kextcache --clear-staging`

then doing

`kextutil /Library/Extensions/360Controller.kext`

does the job even if console throws error, because after completing command I just unplug and replug controller and it's done
