### ISSUE TITLE
RT Constantly Enabled Even if not Pressed

### ISSUE THREAD

**Issue by kdn511** [360Controller/360Controller#923]
### Type of Controller
Replace this text with: Xbox 360 (officially licensed microsoft product)

### OS Version
10.14

### Driver Version
Most Recent

### Connection Method
Wired

### Device Name and Info
(If you don't know this information, please refer to the README for how to find it. Enter N/A if not applicable)
>Device Name:
<br/>Product ID:
<br/>Vendor ID:

### Response of Controller
Everything works when testing controller in the driver

### Response in Preference Pane
Everything reacts perfectly in testing

### Detailed Explaination of Issue
When playing "Madden 08" for MAC, the RT is constantly 'enabled' even though I'm not pressing it. This makes the game nearly impossible to play. I thought it may have been game related, however, I mapped the RT to a mouse movement and when I enable to mapper, the mouse moves in the same direction I mapped even while not even touching the controller. Basically, without touching the controller, when using this driver, it's as if the RT is constantly held down. Very very odd and makes it impossible to play any game via MAC with the 360 controller. Any ideas? Even a work around on how to disable to RT would be appreciated!

**Comment by FranticRain** [comment]
The driver does not provide any sort of compatibility for individual games beyond what is provided in the preference pane. The driver simply sends button data to the operating system. Once it does that, control is out of the driver's hands. Since Apple does not provide any standardized means of interacting with controllers in macOS, every game uses a different method to read controller data. We cannot provide individual fixes for each game within the controller. That simply isn't feasible. It is the responsibility of game developers to support controllers, not the other way around. We cannot and will not provide support for individual games. If you are using an Xbox One controller, we can recommend that you use the "Pretend to be an Xbox 360 Controller" option in the "Advanced" menu for better game compatibility. Beyond that, there is nothing we can do.
